# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agmon < Formula
  desc "Real-time observability for AI coding agents"
  homepage "https://github.com/tt-a1i/agmon"
  version "0.4.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tt-a1i/agmon/releases/download/v0.4.6/agmon_darwin_amd64.tar.gz"
      sha256 "253398e85e993cc19fe3c2ca0141a7c6c0818cb263648498c5d523e68c7f806c"

      define_method(:install) do
        bin.install "agmon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tt-a1i/agmon/releases/download/v0.4.6/agmon_darwin_arm64.tar.gz"
      sha256 "a71de2db083c08cb9da2328a79276e6e36253031b0327f77a5dbc250e9916b77"

      define_method(:install) do
        bin.install "agmon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tt-a1i/agmon/releases/download/v0.4.6/agmon_linux_amd64.tar.gz"
      sha256 "14679965793cb58db10ce25eae6354c7c021b12eea276f063ba2ffe26a88fcba"
      define_method(:install) do
        bin.install "agmon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tt-a1i/agmon/releases/download/v0.4.6/agmon_linux_arm64.tar.gz"
      sha256 "982a0d0a61ecc13e468dc6aa95943862b485907d629d4fb641eaa1977f9eb2ca"
      define_method(:install) do
        bin.install "agmon"
      end
    end
  end
end
