# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenmeter" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "efd527e4c209a50842d251aff27e541f7d81434ac2717a5594268d3ea9f11c2b"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e633af9f714d2d4575014c122e9a53df7165dfd85a86cbc40a8a02684465f428"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4009d38c11854ea4777f8cbb694898162a6cc986bb3359bc64eaeddcfb7e581"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eb40ea151df849ea090348abc4061233590f62f0b7d711bf83f664206bb4c345"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_linux_arm64.tar.gz"
    end
  end

  name "tokenmeter"
  desc "Real-time observability for AI coding agents"
  homepage "https://github.com/tt-a1i/tokenmeter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tm"

  # No zap stanza required

end
