# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenmeter" do
  version "0.8.3"

  on_macos do
    on_intel do
      sha256 "17d384dd072460243495c89f2c6e65da62ec9ee0470d7ff6aed0ff64b918840a"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e8d2c460b2848159b87b62f4fe3e492d8f950ae99065995790186541fdaf67c8"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "06e6df69244b01f79771c313c5adb3edac6893acc5e24585cb46bc8264f48f45"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e66c74eca872c4299643825bc53921238e1360aa5bab58d06271926d2d15272a"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_linux_arm64.tar.gz"
    end
  end

  name "tokenmeter"
  desc "Real-time observability for AI coding agents"
  homepage "https://github.com/tt-a1i/tokenmeter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tm"

  # No zap stanza required

end
