# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenmeter" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "0e06edf38fee1e3ea5ef648b347cce3572910dab09c23ac731e98fdf6bd75985"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d064098f29ae161888d0a8fabbda693bedd27288f1ae7440167d749bf9650ddb"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "522b8284ff121479fec6ee424d61f2f1f3451a7343eb5e1463826a6fc142e20e"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "22a00a4a0f8a82703c7ec7c01f5738a77f69b9344f9dbfeacb2f1e8281808419"
      url "https://github.com/tt-a1i/tokenmeter/releases/download/v#{version}/tokenmeter_linux_arm64.tar.gz"
    end
  end

  name "tokenmeter"
  desc "Real-time observability for AI coding agents"
  homepage "https://github.com/tt-a1i/tokenmeter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tm"

  # No zap stanza required

end
