# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doppel < Formula
  desc "Clone a macOS .app bundle into a second, separately-launchable instance"
  homepage "https://github.com/tt-a1i/doppel"
  version "0.2.1-runtime-test"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tt-a1i/doppel/releases/download/v0.2.1-runtime-test/doppel_0.2.1-runtime-test_darwin_amd64.tar.gz"
    sha256 "435730fdeb9e92aa48ca3a5359b250e08016de68030322bcce5990c56e33201f"

    define_method(:install) do
      bin.install "doppel"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tt-a1i/doppel/releases/download/v0.2.1-runtime-test/doppel_0.2.1-runtime-test_darwin_arm64.tar.gz"
    sha256 "cdf993a94bfb28e89df748b504aa47f3c2bdce99a2bb88521075248076b29018"

    define_method(:install) do
      bin.install "doppel"
    end
  end

  def caveats
    <<~EOS
      doppel is distributed as an unsigned binary — macOS Gatekeeper will
      prompt on first launch. If the command is blocked, run:

        xattr -dr com.apple.quarantine "$(brew --prefix)/bin/doppel"
    EOS
  end

  test do
    system "#{bin}/doppel", "--help"
  end
end
