# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doppel < Formula
  desc "Clone a macOS .app bundle into a second, separately-launchable instance"
  homepage "https://github.com/tt-a1i/doppel"
  version "0.0.1-rc1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tt-a1i/doppel/releases/download/v0.0.1-rc1/doppel_0.0.1-rc1_darwin_amd64.tar.gz"
    sha256 "63c698224143b5d1b7f83221ba24ea0aebae407610ce6f15bfaf706e5b9b0b69"

    define_method(:install) do
      bin.install "doppel"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tt-a1i/doppel/releases/download/v0.0.1-rc1/doppel_0.0.1-rc1_darwin_arm64.tar.gz"
    sha256 "1d6a9fe145de6a8e71f5312dd7ba8fc70d7ce65788185a990ab6cb3945d954f3"

    define_method(:install) do
      bin.install "doppel"
    end
  end

  def caveats
    <<~EOS
      doppel is distributed as an unsigned binary — macOS Gatekeeper will
      prompt on first launch. If the command is blocked, run:

        xattr -dr com.apple.quarantine "$(brew --prefix)/bin/doppel"
    EOS
  end

  test do
    system "#{bin}/doppel", "--help"
  end
end
