# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doppel < Formula
  desc "Clone a macOS .app bundle into a second, separately-launchable instance"
  homepage "https://github.com/tt-a1i/doppel"
  version "0.2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tt-a1i/doppel/releases/download/v0.2.0/doppel_0.2.0_darwin_amd64.tar.gz"
    sha256 "d35c2bc04260b3d95625858f88546dd88f5c2e8b76b4513ccba3c3389d03aac3"

    define_method(:install) do
      bin.install "doppel"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tt-a1i/doppel/releases/download/v0.2.0/doppel_0.2.0_darwin_arm64.tar.gz"
    sha256 "96d067c67add4419fb2fe3c6e0492cd7cbc08b16853b9fabe6e083cd54712175"

    define_method(:install) do
      bin.install "doppel"
    end
  end

  def caveats
    <<~EOS
      doppel is distributed as an unsigned binary — macOS Gatekeeper will
      prompt on first launch. If the command is blocked, run:

        xattr -dr com.apple.quarantine "$(brew --prefix)/bin/doppel"
    EOS
  end

  test do
    system "#{bin}/doppel", "--help"
  end
end
